// cycle 127: gated on the monorepo shared fixtures (include_str! below); cfg'd out in a
// standalone CI checkout where they're absent. Set by build.rs.
#![cfg(has_shared_fixtures)]
//! Cross-platform test vector validation (GAP-08-003)
//!
//! Consumes canonical test vectors generated by the Kotlin SDK to ensure
//! cryptographic compatibility across all KnishIO SDK implementations.

use std::collections::HashMap;
use serde::Deserialize;

// Import the Rust SDK's public API
use base64::Engine as _;
use knishio_client::{shake256, generate_bundle_hash, Wallet, Atom};
use knishio_client::wallet::EncryptedMessage;
use knishio_client::types::{Isotope, MetaItem};
use knishio_client::crypto::{
    enumerate_hash, normalize_hash,
    generate_ots_signature, verify_ots_signature,
};

// ── Test vector JSON structures ─────────────────────────────────────────

#[derive(Deserialize)]
struct TestVectors {
    vectors: Vectors,
}

#[derive(Deserialize)]
struct Vectors {
    shake256: Shake256Section,
    bundle_hash: BundleHashSection,
    wallet_generation: WalletGenerationSection,
    hash_normalization: HashNormalizationSection,
    molecular_hash: MolecularHashSection,
    wots_signature: WotsSignatureSection,
    mlkem768: Mlkem768Section,
    #[serde(default)]
    mlkem1024: Option<Mlkem768Section>,
    #[serde(rename = "legacyMlkem768AuthMolecule", default)]
    legacy_mlkem768_auth_molecule: Option<LegacyMlkem768AuthMolecule>,
    edge_cases: EdgeCasesSection,
}

// ── SHAKE256 ────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct Shake256Section {
    tests: Vec<Shake256Test>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Shake256Test {
    name: String,
    input: String,
    output_length: usize,
    expected: String,
}

// ── Bundle hash ─────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct BundleHashSection {
    tests: Vec<BundleHashTest>,
}

#[derive(Deserialize)]
struct BundleHashTest {
    name: String,
    secret: String,
    expected: String,
}

// ── Wallet generation ───────────────────────────────────────────────────

#[derive(Deserialize)]
struct WalletGenerationSection {
    tests: Vec<WalletGenerationTest>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct WalletGenerationTest {
    name: String,
    secret: String,
    token: String,
    position: String,
    expected_bundle: String,
    expected_address: String,
    #[serde(default)]
    expected_private_key: Option<String>,
    #[serde(default)]
    expected_public_key: Option<String>,
}

// ── Hash normalization (WOTS+) ──────────────────────────────────────────

#[derive(Deserialize)]
struct HashNormalizationSection {
    tests: Vec<HashNormalizationTest>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct HashNormalizationTest {
    name: String,
    hash: String,
    expected_enumerated: HashMap<String, i8>,
    expected_normalized: HashMap<String, i8>,
}

// ── Molecular hash ──────────────────────────────────────────────────────

#[derive(Deserialize)]
struct MolecularHashSection {
    tests: Vec<MolecularHashTest>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct MolecularHashTest {
    name: String,
    atoms: Vec<MolecularHashAtom>,
    expected_hash: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct MolecularHashAtom {
    position: String,
    wallet_address: String,
    isotope: String,
    token: String,
    #[serde(default)]
    value: Option<String>,
    #[serde(default)]
    meta_type: Option<String>,
    #[serde(default)]
    meta_id: Option<String>,
    #[serde(default)]
    meta: Vec<TestMetaItem>,
    index: u32,
    created_at: String,
}

#[derive(Deserialize, Clone)]
struct TestMetaItem {
    key: String,
    value: String,
}

// ── WOTS+ signature ─────────────────────────────────────────────────────

#[derive(Deserialize)]
struct WotsSignatureSection {
    tests: Vec<WotsSignatureTest>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct WotsSignatureTest {
    name: String,
    private_key: String,
    molecular_hash: String,
    expected_signature_fragments: String,
    expected_compressed_signature: String,
}

// ── Edge cases ──────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct EdgeCasesSection {
    tests: EdgeCaseTests,
}

#[derive(Deserialize)]
struct EdgeCaseTests {
    unicode_handling: UnicodeHandling,
    boundary_values: BoundaryValues,
    #[serde(default)]
    large_inputs: Option<serde_json::Value>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct UnicodeHandling {
    inputs: Vec<String>,
    expected_hashes: Vec<String>,
}

#[derive(Deserialize)]
struct BoundaryValues {
    cases: Vec<BoundaryCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct BoundaryCase {
    description: String,
    input: String,
    input_length: usize,
    expected_hash: String,
}

// ── ML-KEM768 (post-quantum cipher convergence) ─────────────────────────

#[derive(Deserialize)]
struct Mlkem768Section {
    keygen: Mlkem768Keygen,
    decrypt: Mlkem768Decrypt,
}

// Keygen-from-seed is deterministic (FIPS-203) → byte-frozen pubkey, like a SHAKE vector.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Mlkem768Keygen {
    secret: String,
    token: String,
    position: String,
    expected_pubkey: String,
}

// Encapsulation is non-deterministic, but decapsulation + AES-256-GCM decrypt is deterministic →
// one frozen {cipherText, encryptedMessage} sample must decrypt to the canonical plaintext.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Mlkem768Decrypt {
    secret: String,
    token: String,
    position: String,
    cipher_text: String,
    encrypted_message: String,
    expected_plaintext: String,
}

// ── Frozen pre-bump ML-KEM-768 auth molecule ────────────────────────────

// A signed U+I auth molecule whose U-atom `walletPubkey` meta is a 1184-byte ML-KEM-768 key —
// the shape an 0.9.x client produced. Every SDK must validate it from a build whose default
// parameter set is ML-KEM-1024.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct LegacyMlkem768AuthMolecule {
    expected_molecular_hash: String,
    expected_wallet_pubkey_bytes: usize,
    atoms: Vec<MolecularHashAtom>,
    molecule: serde_json::Value,
}

// ── Load vectors at compile time ────────────────────────────────────────

// Shared cross-SDK master (same source as patent_vector_validation.rs → ../../../sdks/shared-test-results/)
const VECTORS_JSON: &str = include_str!("../../../sdks/shared-test-results/cross-platform-test-vectors.json");

fn load_vectors() -> TestVectors {
    serde_json::from_str(VECTORS_JSON)
        .expect("Failed to parse cross-platform test vectors JSON")
}

/// Helper: construct Atom from test vector data
fn atom_from_vector(a: &MolecularHashAtom) -> Atom {
    let isotope = Isotope::from_str(&a.isotope)
        .unwrap_or_else(|| panic!("Unknown isotope: {}", a.isotope));
    let mut atom = Atom::new(&a.position, &a.wallet_address, isotope, &a.token);
    atom.value = a.value.clone();
    atom.meta_type = a.meta_type.clone();
    atom.meta_id = a.meta_id.clone();
    atom.meta = a.meta.iter().map(|m| MetaItem::new(&m.key, &m.value)).collect();
    atom.index = Some(a.index);
    atom.created_at = a.created_at.clone();
    atom
}

// ════════════════════════════════════════════════════════════════════════
// SHAKE256 tests
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_shake256_cross_platform() {
    let vectors = load_vectors();

    for test in &vectors.vectors.shake256.tests {
        // Rust shake256() takes output length in BITS, vectors use BYTES
        let result = shake256(&test.input, test.output_length * 8);
        assert_eq!(
            result, test.expected,
            "SHAKE256 mismatch for vector '{}': input={:?}, outputLength={} bytes",
            test.name, test.input, test.output_length
        );
    }
}

// ════════════════════════════════════════════════════════════════════════
// Bundle hash tests
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_bundle_hash_cross_platform() {
    let vectors = load_vectors();

    for test in &vectors.vectors.bundle_hash.tests {
        let result = generate_bundle_hash(&test.secret);
        assert_eq!(
            result, test.expected,
            "Bundle hash mismatch for vector '{}': secret={:?}",
            test.name, test.secret
        );
    }
}

// ════════════════════════════════════════════════════════════════════════
// Wallet generation tests
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_wallet_address_cross_platform() {
    let vectors = load_vectors();

    for test in &vectors.vectors.wallet_generation.tests {
        let wallet = Wallet::create(
            Some(&test.secret),
            None,
            &test.token,
            Some(&test.position),
            None,
            None,
        ).unwrap_or_else(|e| panic!(
            "Wallet creation failed for vector '{}': {:?}", test.name, e
        ));

        let bundle = wallet.bundle.as_deref().unwrap_or("");
        assert_eq!(
            bundle, test.expected_bundle,
            "Bundle mismatch for vector '{}': secret={:?}, token={:?}",
            test.name, test.secret, test.token
        );

        let address = wallet.address.as_deref().unwrap_or("");
        assert_eq!(
            address, test.expected_address,
            "Address mismatch for vector '{}': secret={:?}, token={:?}",
            test.name, test.secret, test.token
        );
    }
}

// ════════════════════════════════════════════════════════════════════════
// Hash normalization tests (WOTS+ enumerate + normalize)
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_enumerate_hash_cross_platform() {
    let vectors = load_vectors();

    for test in &vectors.vectors.hash_normalization.tests {
        let result = enumerate_hash(&test.hash);
        assert_eq!(result.len(), 64,
            "enumerate_hash output length must be 64 for '{}'", test.name);
        for (idx_str, &expected) in &test.expected_enumerated {
            let idx: usize = idx_str.parse().unwrap();
            assert_eq!(
                result[idx], expected,
                "enumerate_hash mismatch for '{}' at index {}: got {}, expected {}",
                test.name, idx, result[idx], expected
            );
        }
    }
}

#[test]
fn test_normalize_hash_cross_platform() {
    let vectors = load_vectors();

    for test in &vectors.vectors.hash_normalization.tests {
        let result = normalize_hash(&test.hash);
        assert_eq!(result.len(), 64,
            "normalize_hash output length must be 64 for '{}'", test.name);
        for (idx_str, &expected) in &test.expected_normalized {
            let idx: usize = idx_str.parse().unwrap();
            assert_eq!(
                result[idx], expected,
                "normalize_hash mismatch for '{}' at index {}: got {}, expected {}",
                test.name, idx, result[idx], expected
            );
        }
    }
}

/// Whitepaper requirement: normalized hash values MUST sum to exactly 0
#[test]
fn test_normalized_hash_sum_zero_invariant() {
    let vectors = load_vectors();

    for test in &vectors.vectors.hash_normalization.tests {
        let normalized = normalize_hash(&test.hash);
        let sum: i32 = normalized.iter().map(|&v| v as i32).sum();
        assert_eq!(sum, 0,
            "Normalized hash sum must be 0 for '{}', got {}", test.name, sum);
    }
}

// ════════════════════════════════════════════════════════════════════════
// Molecular hash tests
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_molecular_hash_cross_platform() {
    // The test vectors use fixed timestamps; override the Atom timestamp generator
    std::env::set_var("KNISHIO_FIXED_TIMESTAMP", "1640995200000");

    let vectors = load_vectors();

    for test in &vectors.vectors.molecular_hash.tests {
        let atoms: Vec<Atom> = test.atoms.iter().map(atom_from_vector).collect();
        let hash = Atom::hash_atoms(&atoms, "base17")
            .unwrap_or_else(|e| panic!("hash_atoms failed for '{}': {:?}", test.name, e));
        assert_eq!(
            hash, test.expected_hash,
            "Molecular hash mismatch for '{}'\n  got:      {}\n  expected: {}",
            test.name, hash, test.expected_hash
        );
    }

    std::env::remove_var("KNISHIO_FIXED_TIMESTAMP");
}

/// Whitepaper: molecular hash must change when any atom field is tampered
#[test]
fn test_molecular_hash_tamper_detection() {
    std::env::set_var("KNISHIO_FIXED_TIMESTAMP", "1640995200000");

    let vectors = load_vectors();
    let test = &vectors.vectors.molecular_hash.tests[0]; // single_atom_molecule
    let atoms: Vec<Atom> = test.atoms.iter().map(atom_from_vector).collect();
    let original_hash = Atom::hash_atoms(&atoms, "base17").unwrap();

    // Tamper: change the token
    let mut tampered = atoms.clone();
    tampered[0].token = "TAMPERED".to_string();
    let tampered_hash = Atom::hash_atoms(&tampered, "base17").unwrap();
    assert_ne!(original_hash, tampered_hash,
        "Molecular hash must change when atom token is tampered");

    // Tamper: change the value
    let mut tampered2 = atoms.clone();
    tampered2[0].value = Some("999".to_string());
    let tampered_hash2 = Atom::hash_atoms(&tampered2, "base17").unwrap();
    assert_ne!(original_hash, tampered_hash2,
        "Molecular hash must change when atom value is tampered");

    std::env::remove_var("KNISHIO_FIXED_TIMESTAMP");
}

// ════════════════════════════════════════════════════════════════════════
// WOTS+ signature tests
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_wots_signature_cross_platform() {
    let vectors = load_vectors();

    for test in &vectors.vectors.wots_signature.tests {
        let fragments = generate_ots_signature(&test.private_key, &test.molecular_hash).unwrap();
        assert_eq!(fragments.len(), 16,
            "OTS must produce 16 fragments for '{}'", test.name);
        // Rust's generate_ots_signature uses normalize_hash + (8-n) iterations,
        // which matches the Kotlin SDK's "compressed signature" output.
        // The Kotlin "fragments" field uses a different intermediate representation.
        let concatenated = fragments.join("");
        assert_eq!(
            concatenated, test.expected_compressed_signature,
            "OTS signature mismatch for '{}'\n  got len:      {}\n  expected len: {}",
            test.name, concatenated.len(), test.expected_compressed_signature.len()
        );
    }
}

/// Verify that a signature generated from a known private key can be verified.
///
/// Note: verify_ots_signature reconstructs the verification address with the two-pass
/// derivation (digest = SHAKE256(joined, 8192); address = SHAKE256(digest, 256)),
/// matching generate_address() and CheckMolecule::ots. We compute the expected OTS
/// address the same way.
#[test]
fn test_wots_signature_verification_roundtrip() {
    let vectors = load_vectors();

    for test in &vectors.vectors.wots_signature.tests {
        let fragments = generate_ots_signature(&test.private_key, &test.molecular_hash).unwrap();

        // Compute expected OTS verification address: hash each key chunk 16 times
        // (matching sign iterations 8-n + verify iterations 8+n = 16), then derive the
        // address two-pass: digest = SHAKE256(joined, 8192); address = SHAKE256(digest, 256)
        // (matches generate_address / CheckMolecule::ots).
        let mut public_key_fragments = Vec::new();
        for i in 0..16 {
            let start = i * 128;
            let chunk = &test.private_key[start..start + 128];
            let mut working = chunk.to_string();
            for _ in 0..16 {
                working = shake256(&working, 512);
            }
            public_key_fragments.push(working);
        }
        let joined = public_key_fragments.join("");
        let digest = shake256(&joined, 8192);
        let ots_address = shake256(&digest, 256);

        let verified = verify_ots_signature(&fragments, &test.molecular_hash, &ots_address);
        assert!(verified,
            "OTS signature must verify for '{}' with OTS address {}", test.name, ots_address);
    }
}

// ════════════════════════════════════════════════════════════════════════
// Edge case tests
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_unicode_shake256_cross_platform() {
    let vectors = load_vectors();
    let unicode = &vectors.vectors.edge_cases.tests.unicode_handling;

    for (i, (input, expected)) in unicode.inputs.iter().zip(unicode.expected_hashes.iter()).enumerate() {
        let result = shake256(input, 256);
        assert_eq!(
            &result, expected,
            "Unicode SHAKE256 mismatch at index {} for input {:?}", i, input
        );
    }
}

#[test]
fn test_boundary_shake256_cross_platform() {
    let vectors = load_vectors();

    for case in &vectors.vectors.edge_cases.tests.boundary_values.cases {
        assert_eq!(case.input.len(), case.input_length,
            "Test vector input length mismatch for '{}'", case.description);
        let result = shake256(&case.input, 256);
        assert_eq!(
            result, case.expected_hash,
            "Boundary SHAKE256 mismatch for '{}' (input length {})",
            case.description, case.input_length
        );
    }
}

/// Whitepaper: all enumerated hash values must be in [-8, 8]
#[test]
fn test_enumerate_hash_range_invariant() {
    let vectors = load_vectors();

    for test in &vectors.vectors.hash_normalization.tests {
        let enumerated = enumerate_hash(&test.hash);
        for (i, &val) in enumerated.iter().enumerate() {
            assert!(
                (-8..=8).contains(&val),
                "enumerate_hash value {} at index {} out of [-8, 8] range for '{}'",
                val, i, test.name
            );
        }
    }
}

// ════════════════════════════════════════════════════════════════════════
// ML-KEM768 tests (post-quantum cipher cross-SDK convergence)
// ════════════════════════════════════════════════════════════════════════

#[test]
fn test_mlkem768_keygen_cross_platform() {
    let vectors = load_vectors();
    let v = &vectors.vectors.mlkem768.keygen;

    let wallet = Wallet::create(
        Some(&v.secret),
        None,
        &v.token,
        Some(&v.position),
        None,
        Some(knishio_client::MlKemParameterSet::MlKem768),
    ).unwrap_or_else(|e| panic!("ML-KEM768 keygen wallet creation failed: {:?}", e));

    // libcrux-ml-kem keygen must byte-match the @noble-derived frozen pubkey.
    assert_eq!(
        wallet.pubkey.as_deref(),
        Some(v.expected_pubkey.as_str()),
        "ML-KEM768 keygen pubkey mismatch (libcrux vs @noble frozen vector)"
    );
}

#[tokio::test]
async fn test_mlkem768_decrypt_cross_platform() {
    let vectors = load_vectors();
    let v = &vectors.vectors.mlkem768.decrypt;

    let wallet = Wallet::create(
        Some(&v.secret),
        None,
        &v.token,
        Some(&v.position),
        None,
        Some(knishio_client::MlKemParameterSet::MlKem768),
    ).unwrap_or_else(|e| panic!("ML-KEM768 decrypt wallet creation failed: {:?}", e));

    let em = EncryptedMessage {
        cipher_text: v.cipher_text.clone(),
        encrypted_message: v.encrypted_message.clone(),
    };

    // libcrux decapsulation + AES-256-GCM must recover the @noble-encapsulated plaintext.
    let plaintext = wallet.decrypt_message(&em).await
        .unwrap_or_else(|e| panic!("ML-KEM768 decrypt failed: {:?}", e));

    assert_eq!(
        plaintext.as_str(),
        Some(v.expected_plaintext.as_str()),
        "ML-KEM768 decrypt plaintext mismatch (frozen @noble sample via libcrux)"
    );
}
#[test]
fn test_mlkem1024_keygen_cross_platform() {
    let vectors = load_vectors();
    let v = vectors.vectors.mlkem1024.as_ref().expect("mlkem1024 section missing");
    let keygen = &v.keygen;

    let wallet = Wallet::create(
        Some(&keygen.secret),
        None,
        &keygen.token,
        Some(&keygen.position),
        None,
        None,
    ).unwrap_or_else(|e| panic!("ML-KEM1024 keygen wallet creation failed: {:?}", e));

    assert_eq!(
        wallet.pubkey.as_deref(),
        Some(keygen.expected_pubkey.as_str()),
        "ML-KEM1024 keygen pubkey mismatch (libcrux vs @noble frozen vector)"
    );
}

#[tokio::test]
async fn test_mlkem1024_decrypt_cross_platform() {
    let vectors = load_vectors();
    let v = vectors.vectors.mlkem1024.as_ref().expect("mlkem1024 section missing");
    let decrypt = &v.decrypt;

    let wallet = Wallet::create(
        Some(&decrypt.secret),
        None,
        &decrypt.token,
        Some(&decrypt.position),
        None,
        None,
    ).unwrap_or_else(|e| panic!("ML-KEM1024 decrypt wallet creation failed: {:?}", e));

    let em = EncryptedMessage {
        cipher_text: decrypt.cipher_text.clone(),
        encrypted_message: decrypt.encrypted_message.clone(),
    };

    let plaintext = wallet.decrypt_message(&em).await
        .unwrap_or_else(|e| panic!("ML-KEM1024 decrypt failed: {:?}", e));

    assert_eq!(
        plaintext.as_str(),
        Some(decrypt.expected_plaintext.as_str()),
        "ML-KEM1024 decrypt plaintext mismatch (frozen @noble sample via libcrux)"
    );
}

// ════════════════════════════════════════════════════════════════════════
// Backwards compatibility: an ML-KEM-1024 default build reads pre-bump 768 records
// ════════════════════════════════════════════════════════════════════════

/// Build the wallet from `vectors.mlkem768.decrypt` at an explicit parameter set.
fn legacy_decrypt_wallet(v: &Mlkem768Decrypt, set: Option<knishio_client::MlKemParameterSet>) -> Wallet {
    Wallet::create(Some(&v.secret), None, &v.token, Some(&v.position), None, set)
        .unwrap_or_else(|e| panic!("wallet creation failed: {:?}", e))
}

fn decoded_len(b64: &str) -> usize {
    base64::engine::general_purpose::STANDARD
        .decode(b64)
        .unwrap_or_else(|e| panic!("invalid base64: {:?}", e))
        .len()
}

/// (a) A wallet at the DEFAULT parameter set (ML-KEM-1024) decrypts the frozen ML-KEM-768
/// envelope directly — no second wallet, no explicit step-back — and (b) still advertises its
/// own 1568-byte ML-KEM-1024 public key, because dual-identity decryption must not move what
/// the wallet advertises into molecule meta and auth.
#[tokio::test]
async fn test_default_1024_wallet_decrypts_frozen_768_envelope() {
    let vectors = load_vectors();
    let v = &vectors.vectors.mlkem768.decrypt;

    let wallet = legacy_decrypt_wallet(v, None);

    // (b) the advertised key is still ML-KEM-1024
    assert_eq!(
        decoded_len(wallet.pubkey.as_deref().expect("default wallet pubkey")),
        1568,
        "a default wallet must still advertise an ML-KEM-1024 public key"
    );

    let em = EncryptedMessage {
        cipher_text: v.cipher_text.clone(),
        encrypted_message: v.encrypted_message.clone(),
    };
    assert_eq!(decoded_len(&em.cipher_text), 1088, "frozen envelope must be a 768 ciphertext");

    // (a) permissive inbound: the 768 identity is derived on demand from the same wallet seed
    let plaintext = wallet.decrypt_message(&em).await
        .unwrap_or_else(|e| panic!("default-1024 wallet failed to decrypt the frozen 768 envelope: {:?}", e));

    assert_eq!(plaintext.as_str(), Some(v.expected_plaintext.as_str()));
}

/// (d) A ciphertext matching neither parameter set still fails on the existing observable —
/// this SDK returns `Err(KnishIOError::DecryptionKey)`.
#[tokio::test]
async fn test_default_1024_wallet_rejects_unknown_ciphertext_length() {
    let vectors = load_vectors();
    let v = &vectors.vectors.mlkem768.decrypt;

    let wallet = legacy_decrypt_wallet(v, None);
    let em = EncryptedMessage {
        cipher_text: base64::engine::general_purpose::STANDARD.encode([0u8; 64]),
        encrypted_message: v.encrypted_message.clone(),
    };

    assert!(
        wallet.decrypt_message(&em).await.is_err(),
        "a 64-byte ciphertext matches neither parameter set and must still fail"
    );
}

/// (e) The map-addressed `CipherHash` path finds an envelope a pre-bump sender addressed to
/// `hashShare(our_768_pubkey)`. Without the second hash-share lookup the wallet returns before
/// any decryption is attempted, so (a)'s length dispatch is unreachable on this path.
#[tokio::test]
async fn test_default_1024_wallet_finds_768_addressed_cipher_hash_envelope() {
    let vectors = load_vectors();
    let v = &vectors.vectors.mlkem768.decrypt;

    let wallet_768 = legacy_decrypt_wallet(v, Some(knishio_client::MlKemParameterSet::MlKem768));
    let pubkey_768 = wallet_768.pubkey.as_deref().expect("768 wallet pubkey");
    assert_eq!(decoded_len(pubkey_768), 1184);

    let mut map: HashMap<String, EncryptedMessage> = HashMap::new();
    map.insert(
        Wallet::hash_share(pubkey_768),
        EncryptedMessage {
            cipher_text: v.cipher_text.clone(),
            encrypted_message: v.encrypted_message.clone(),
        },
    );

    let wallet = legacy_decrypt_wallet(v, None);
    assert!(
        !map.contains_key(&Wallet::hash_share(wallet.pubkey.as_deref().unwrap())),
        "the envelope must NOT be addressed to the configured (1024) identity"
    );

    // Returns the RAW decrypted text — the frozen payload is a JSON-encoded string.
    let raw = wallet.decrypt_my_message_ml(&map).await
        .expect("default-1024 wallet must find and decrypt the 768-addressed envelope");
    let parsed: serde_json::Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("raw decrypted text is not JSON: {:?} ({})", e, raw));

    assert_eq!(parsed.as_str(), Some(v.expected_plaintext.as_str()));
}

// ════════════════════════════════════════════════════════════════════════
// Frozen pre-bump ML-KEM-768 auth molecule (validated from a 1024 default build)
// ════════════════════════════════════════════════════════════════════════

fn legacy_molecule_vector(vectors: &TestVectors) -> &LegacyMlkem768AuthMolecule {
    vectors
        .vectors
        .legacy_mlkem768_auth_molecule
        .as_ref()
        .expect("legacyMlkem768AuthMolecule section missing")
}

/// The frozen record really is a 768 record (its U-atom `walletPubkey` decodes to 1184 bytes),
/// and its molecular hash still verifies under the same hashing function the
/// `vectors.molecular_hash` cases use. The byte-length assertion fails loudly if the fixture is
/// ever regenerated at ML-KEM-1024.
#[test]
fn test_legacy_768_auth_molecule_hash_cross_platform() {
    let vectors = load_vectors();
    let v = legacy_molecule_vector(&vectors);

    let pubkeys: Vec<&str> = v.molecule["atoms"]
        .as_array()
        .expect("molecule.atoms array")
        .iter()
        .filter_map(|atom| atom["meta"].as_array())
        .flatten()
        .filter(|meta| meta["key"].as_str() == Some("walletPubkey"))
        .filter_map(|meta| meta["value"].as_str())
        .collect();

    assert_eq!(pubkeys.len(), 1, "exactly one walletPubkey meta expected");
    assert_eq!(
        decoded_len(pubkeys[0]),
        v.expected_wallet_pubkey_bytes,
        "the fixture is no longer an ML-KEM-768 record"
    );
    assert_eq!(v.expected_wallet_pubkey_bytes, 1184);

    let atoms: Vec<Atom> = v.atoms.iter().map(atom_from_vector).collect();
    let hash = Atom::hash_atoms(&atoms, "base17")
        .unwrap_or_else(|e| panic!("hash_atoms failed for the legacy 768 molecule: {:?}", e));

    assert_eq!(
        hash, v.expected_molecular_hash,
        "legacy 768 auth molecule hash mismatch\n  got:      {}\n  expected: {}",
        hash, v.expected_molecular_hash
    );
}

/// Full validation: deserialize the frozen molecule and run the SDK's `check` (molecular hash +
/// WOTS+ OTS) from a build whose default parameter set is ML-KEM-1024.
#[test]
fn test_legacy_768_auth_molecule_full_check() {
    let vectors = load_vectors();
    let v = legacy_molecule_vector(&vectors);

    let json = serde_json::to_string(&v.molecule).expect("molecule re-serialization");
    let molecule = knishio_client::Molecule::fromJSON(&json)
        .unwrap_or_else(|e| panic!("legacy 768 molecule deserialization failed: {:?}", e));

    assert_eq!(molecule.molecular_hash.as_deref(), Some(v.expected_molecular_hash.as_str()));

    let source_wallet = molecule
        .source_wallet
        .clone()
        .expect("molecule.sourceWallet reconstructed");

    let valid = molecule.check(Some(&source_wallet))
        .unwrap_or_else(|e| panic!("legacy 768 molecule check failed: {:?}", e));

    assert!(valid, "a 1024-default build must validate a pre-bump 768 molecule");
}

#[path = "fixtures/mod.rs"]
mod fixtures;

#[test]
fn test_secret_storage_envelope_constant_matches_master_vector() {
    let v: serde_json::Value = serde_json::from_str(VECTORS_JSON).expect("valid vectors JSON");
    let master_payload = &v["vectors"]["secret_storage_envelope"]["tests"][0]["payload"];
    let parsed_frozen: serde_json::Value = serde_json::from_str(fixtures::FROZEN_TS_ENVELOPE).expect("valid JSON");
    assert_eq!(&parsed_frozen, master_payload, "inline FROZEN_TS_ENVELOPE must match the master vector");
}
